#!/bin/sh
# Renders nitter's runtime config from environment variables, then execs nitter.
#
# On Heroku the filesystem is ephemeral and $PORT is assigned per boot, so
# nitter.conf and sessions.jsonl cannot be baked into the image. Nitter reads
# NITTER_CONF_FILE and NITTER_SESSIONS_FILE, so everything is rendered to /tmp
# and the image's own files are left alone.
#
# When REDIS_URL is unset this script does nothing but exec, so the plain
# docker/compose path (which mounts /src/nitter.conf read-only) is unaffected.
#
# Set NITTER_ENTRYPOINT_DRY_RUN=1 to render the config files and exit without
# starting stunnel or nitter. Used by tests/test_entrypoint.sh.

set -eu

CONF_FILE="${NITTER_CONF_FILE:-/tmp/nitter.conf}"
SESSIONS_FILE="${NITTER_SESSIONS_FILE:-/tmp/sessions.jsonl}"
STUNNEL_CONF="${STUNNEL_CONF:-/tmp/stunnel.conf}"
STATIC_DIR="${NITTER_STATIC_DIR:-./public}"

die() {
  echo "entrypoint: $1" >&2
  exit 1
}

# Splits a redis:// or rediss:// URL into REDIS_SCHEME/HOST/PORT/PASSWORD.
# Both expansions below key off the *last* '@', so a password containing '@'
# still parses correctly.
parse_redis_url() {
  url="$1"

  case "$url" in
    rediss://*) REDIS_SCHEME=rediss ;;
    redis://*)  REDIS_SCHEME=redis ;;
    *) die "REDIS_URL must start with redis:// or rediss://, got '${url%%:*}:'" ;;
  esac

  rest="${url#*://}"
  case "$rest" in
    *@*)
      userinfo="${rest%@*}"
      hostport="${rest##*@}"
      ;;
    *)
      userinfo=""
      hostport="$rest"
      ;;
  esac

  # userinfo is [user]:[password]; nitter only sends the password via AUTH.
  case "$userinfo" in
    *:*) REDIS_PASSWORD="${userinfo#*:}" ;;
    *)   REDIS_PASSWORD="" ;;
  esac

  hostport="${hostport%%/*}"
  case "$hostport" in
    *:*)
      REDIS_HOST="${hostport%:*}"
      REDIS_PORT="${hostport##*:}"
      ;;
    *)
      REDIS_HOST="$hostport"
      REDIS_PORT=6379
      ;;
  esac

  [ -n "$REDIS_HOST" ] || die "could not parse a host out of REDIS_URL"
}

write_stunnel_conf() {
  cat > "$STUNNEL_CONF" <<EOF
; Generated by docker-entrypoint.sh -- do not edit.
; Heroku Key-Value Store requires TLS, but nitter's redis client
; (redpool -> nim-lang/redis) only speaks plaintext. stunnel bridges the two.
pid = /tmp/stunnel.pid
foreground = no
syslog = no
output = /dev/stdout
debug = ${STUNNEL_DEBUG:-4}

[redis]
client = yes
accept = 127.0.0.1:${LOCAL_REDIS_PORT}
connect = ${REDIS_HOST}:${REDIS_PORT}
; Heroku Key-Value Store presents a self-signed certificate.
verifyChain = no
verifyPeer = no
EOF
}

write_nitter_conf() {
  cat > "$CONF_FILE" <<EOF
# Generated by docker-entrypoint.sh -- do not edit.
[Server]
hostname = "${NITTER_HOSTNAME}"
title = "${NITTER_TITLE:-nitter}"
address = "0.0.0.0"
port = ${PORT:-8080}
https = ${NITTER_HTTPS:-true}
httpMaxConnections = ${NITTER_HTTP_MAX_CONNECTIONS:-100}
staticDir = "${STATIC_DIR}"

[Cache]
listMinutes = ${NITTER_LIST_MINUTES:-240}
rssMinutes = ${NITTER_RSS_MINUTES:-10}
redisHost = "${NITTER_REDIS_HOST}"
redisPort = ${NITTER_REDIS_PORT}
redisPassword = "${REDIS_PASSWORD}"
# Heroku Key-Value Store Mini caps the instance at 20 connections, so these
# default far below nitter's usual 20/30.
redisConnections = ${NITTER_REDIS_CONNECTIONS:-4}
redisMaxConnections = ${NITTER_REDIS_MAX_CONNECTIONS:-8}

[Config]
hmacKey = "${NITTER_HMAC_KEY}"
base64Media = ${NITTER_BASE64_MEDIA:-false}
enableRSS = ${NITTER_ENABLE_RSS:-true}
enableRSSUserTweets = true
enableRSSUserReplies = true
enableRSSUserMedia = true
enableRSSUserArticles = true
enableRSSSearch = true
enableRSSList = true
enableDebug = ${NITTER_ENABLE_DEBUG:-false}
proxy = "${NITTER_PROXY:-}"
proxyAuth = "${NITTER_PROXY_AUTH:-}"
apiProxy = "${NITTER_API_PROXY:-}"
disableTid = ${NITTER_DISABLE_TID:-false}
maxConcurrentReqs = ${NITTER_MAX_CONCURRENT_REQS:-2}
maxRetries = ${NITTER_MAX_RETRIES:-1}
retryDelayMs = ${NITTER_RETRY_DELAY_MS:-150}

[Preferences]
theme = "${NITTER_THEME:-Nitter}"
replaceTwitter = "${NITTER_HOSTNAME}"
replaceYouTube = "${NITTER_REPLACE_YOUTUBE:-piped.video}"
replaceReddit = "${NITTER_REPLACE_REDDIT:-teddit.net}"
proxyVideos = ${NITTER_PROXY_VIDEOS:-true}
hlsPlayback = ${NITTER_HLS_PLAYBACK:-false}
infiniteScroll = ${NITTER_INFINITE_SCROLL:-false}
EOF
}

write_sessions_file() {
  if [ -n "${NITTER_SESSIONS_B64:-}" ]; then
    # base64 because sessions.jsonl is multi-line and awkward to pass through
    # `heroku config:set`.
    echo "$NITTER_SESSIONS_B64" | base64 -d > "$SESSIONS_FILE" \
      || die "NITTER_SESSIONS_B64 is not valid base64"
  elif [ -n "${NITTER_SESSIONS:-}" ]; then
    printf '%s\n' "$NITTER_SESSIONS" > "$SESSIONS_FILE"
  else
    die "set NITTER_SESSIONS_B64 to your base64-encoded sessions.jsonl:
  heroku config:set NITTER_SESSIONS_B64=\"\$(base64 -w0 sessions.jsonl)\"
Without account sessions every request to the API fails."
  fi

  [ -s "$SESSIONS_FILE" ] || die "the decoded sessions file is empty"
  chmod 600 "$SESSIONS_FILE"
}

# Heroku chowns the image to an arbitrary UID and applies a 0077 umask, which
# leaves public/ at 600/700. Jester 0.6.0 (jester.nim:188) returns 403 for any
# static file without the o+r bit, so every stylesheet, script and icon fails
# to load and the site renders completely unstyled. The dyno user owns these
# files, so it can widen them back at boot.
fix_static_permissions() {
  [ -d "$STATIC_DIR" ] || return 0

  if chmod -R a+rX "$STATIC_DIR" 2>/dev/null; then
    return 0
  fi

  echo "entrypoint: could not widen permissions on $STATIC_DIR" >&2
}

wait_for_stunnel() {
  i=0
  while [ "$i" -lt 50 ]; do
    if nc -z 127.0.0.1 "$LOCAL_REDIS_PORT" 2>/dev/null; then
      return 0
    fi
    i=$((i + 1))
    sleep 0.2
  done
  die "stunnel did not start listening on 127.0.0.1:$LOCAL_REDIS_PORT"
}

# No REDIS_URL means we're not on Heroku; leave the mounted config alone.
if [ -z "${REDIS_URL:-}" ]; then
  exec "$@"
fi

LOCAL_REDIS_PORT="${LOCAL_REDIS_PORT:-6379}"

parse_redis_url "$REDIS_URL"

if [ "$REDIS_SCHEME" = "rediss" ]; then
  # nitter talks plaintext to stunnel on loopback; stunnel does the TLS.
  NITTER_REDIS_HOST=127.0.0.1
  NITTER_REDIS_PORT="$LOCAL_REDIS_PORT"
else
  # A plaintext provider needs no bridge.
  NITTER_REDIS_HOST="$REDIS_HOST"
  NITTER_REDIS_PORT="$REDIS_PORT"
fi

: "${NITTER_HOSTNAME:=${HEROKU_APP_NAME:+$HEROKU_APP_NAME.herokuapp.com}}"
: "${NITTER_HOSTNAME:=localhost}"

if [ -z "${NITTER_HMAC_KEY:-}" ] || [ "$NITTER_HMAC_KEY" = "secretkey" ]; then
  die "set NITTER_HMAC_KEY to a unique random value:
  heroku config:set NITTER_HMAC_KEY=\"\$(openssl rand -hex 32)\"
It signs media URLs; the default lets anyone forge them."
fi

write_nitter_conf
write_sessions_file
fix_static_permissions
if [ "$REDIS_SCHEME" = "rediss" ]; then
  write_stunnel_conf
fi

if [ -n "${NITTER_ENTRYPOINT_DRY_RUN:-}" ]; then
  echo "entrypoint: dry run, wrote $CONF_FILE and $SESSIONS_FILE"
  exit 0
fi

if [ "$REDIS_SCHEME" = "rediss" ]; then
  echo "entrypoint: starting stunnel -> ${REDIS_HOST}:${REDIS_PORT} (TLS)"
  # Daemon mode: stunnel binds its accept socket before the parent returns.
  stunnel "$STUNNEL_CONF"
  wait_for_stunnel
fi

export NITTER_CONF_FILE="$CONF_FILE"
export NITTER_SESSIONS_FILE="$SESSIONS_FILE"

exec "$@"
